### ISSUE TITLE
Simple: Create a new empty component. 

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/bytebooks#3]
Create a new component Offers.jsx  and add it to the App.jsx. (Add the component below the Sellers)

**Comment by mrgeraffe-kun** [comment]
Hi, Can you please assign this task to me.

**Comment by bishwobista** [comment]
> Hi, Can you please assign this task to me.

Yea sure.

**Comment by mrgeraffe-kun** [comment]
![issue](https://github.com/bishwobista/bytebooks/assets/54975573/6f0dd2c2-e9a9-4a16-b248-b642102d4028)

@bishwobista can you check on this??

**Comment by bishwobista** [comment]
My bad, I didn't add the hacktoberfest-accepted label. I am sorry
