### ISSUE TITLE
Simple: Create a new component

### ISSUE THREAD

**Issue by bishwobista** [bishwobista/bytebooks#4]
Create a new component "Top10.jsx" and add it to the App.jsx. (Add it below the Sellers component)

**Comment by muruga21** [comment]
Hello @bishwobista, may I kindly request to be assigned to this task? I am enthusiastic about participating in this project.

**Comment by bishwobista** [comment]
@muruga21  yea, sure, It's a simple task. I just want to help fellow newcomers like me. ✌️
